module.exports = {
    presets: [
        {
            name: "refine-antd",
            type: "refine-react",
            answers: {
                "ui-framework": "antd",
                "antd-theme-customization": "antd-css",
                "mui-extend-theme": "no",
                "mui-dark-mode": "no",
                "router-provider": "react-router-v6",
                "data-provider": "data-provider-custom-json-rest",
                "auth-provider": "none",
                "antd-example-pages": "no",
                "mui-example-pages": "no",
                "antd-custom-layout": "no",
                "mui-custom-layout": "no",
                "command-palette": "no",
                "i18n-no": "no",
                "i18n-antd": "no",
                "i18n-mui": "no",
                "partytown-builder": "no",
            },
        },
        {
            name: "refine-headless",
            type: "refine-react",
            answers: {
                "ui-framework": "no",
                "antd-theme-customization": "antd-css",
                "mui-extend-theme": "no",
                "mui-dark-mode": "no",
                "router-provider": "react-router-v6",
                "data-provider": "data-provider-custom-json-rest",
                "auth-provider": "none",
                "antd-example-pages": "no",
                "mui-example-pages": "no",
                "antd-custom-layout": "no",
                "mui-custom-layout": "no",
                "command-palette": "no",
                "i18n-no": "no",
                "i18n-antd": "no",
                "i18n-mui": "no",
                "partytown-builder": "no",
            },
        },
        {
            name: "refine-mui",
            type: "refine-react",
            answers: {
                "ui-framework": "mui",
                "antd-theme-customization": "antd-css",
                "mui-extend-theme": "no",
                "mui-dark-mode": "no",
                "router-provider": "react-router-v6",
                "data-provider": "data-provider-custom-json-rest",
                "auth-provider": "none",
                "antd-example-pages": "no",
                "mui-example-pages": "no",
                "antd-custom-layout": "no",
                "mui-custom-layout": "no",
                "command-palette": "no",
                "i18n-no": "no",
                "i18n-antd": "no",
                "i18n-mui": "no",
                "partytown-builder": "no",
            },
        },
        {
            name: "refine-headless-remix",
            type: "refine-remix",
            answers: {
                "ui-framework": "no",
                "mui-extend-theme": "no",
                "mui-dark-mode": "no",
                "data-provider": "data-provider-custom-json-rest",
                "auth-provider": "none",
                "antd-example-pages": "no",
                "mui-example-pages": "no",
                "antd-custom-layout": "no",
                "mui-custom-layout": "no",
                "command-palette": "no",
            },
        },
        {
            name: "refine-antd-nextjs",
            type: "refine-nextjs",
            answers: {
                "ui-framework": "antd",
                "antd-theme-customization": "antd-css",
                "mui-extend-theme": "no",
                "mui-dark-mode": "no",
                "data-provider": "data-provider-custom-json-rest",
                "auth-provider": "none",
                "antd-example-pages": "no",
                "mui-example-pages": "no",
                "antd-custom-layout": "no",
                "mui-custom-layout": "no",
                "command-palette": "no",
                "i18n-no": "no",
                "i18n-antd": "no",
                "i18n-mui": "no",
                "partytown-builder": "no",
            },
        },
    ],
};
