module.exports = {
    presets: [
        {
            name: "refine-antd",
            type: "refine-react",
            answers: {
                "ui-framework": "antd",
                "mui-extend-theme": "no",
                "mui-dark-mode": "no",
                "router-provider": "react-router-v6",
                "data-provider": "data-provider-custom-json-rest",
                "auth-provider": "none",
                "antd-example-pages": "no",
                "mui-example-pages": "no",
                "antd-custom-layout": "no",
                "mui-custom-layout": "no",
                "command-palette": "no",
                "i18n-no": "no",
                "i18n-antd": "no",
                "i18n-mui": "no",
                "partytown-builder": "no",
                "inferencer": "no",
            },
        },
        {
            name: "refine-headless",
            type: "refine-react",
            answers: {
                "ui-framework": "no",
                "mui-extend-theme": "no",
                "mui-dark-mode": "no",
                "router-provider": "react-router-v6",
                "data-provider": "data-provider-custom-json-rest",
                "auth-provider": "none",
                "antd-example-pages": "no",
                "mui-example-pages": "no",
                "antd-custom-layout": "no",
                "mui-custom-layout": "no",
                "command-palette": "no",
                "i18n-no": "no",
                "i18n-antd": "no",
                "i18n-mui": "no",
                "partytown-builder": "no",
                "inferencer": "no",
            },
        },
        {
            name: "refine-mui",
            type: "refine-react",
            answers: {
                "ui-framework": "mui",
                "mui-extend-theme": "no",
                "mui-dark-mode": "no",
                "router-provider": "react-router-v6",
                "data-provider": "data-provider-custom-json-rest",
                "auth-provider": "none",
                "antd-example-pages": "no",
                "mui-example-pages": "no",
                "antd-custom-layout": "no",
                "mui-custom-layout": "no",
                "command-palette": "no",
                "i18n-no": "no",
                "i18n-antd": "no",
                "i18n-mui": "no",
                "partytown-builder": "no",
                "inferencer": "no",
            },
        },
        {
            name: "refine-mantine",
            type: "refine-react",
            answers: {
                'ui-framework': 'mantine',
                'mui-extend-theme': 'no',
                'mui-dark-mode': 'no',
                'mantine-dark-mode': 'no',
                'router-provider': 'react-router-v6',
                'data-provider': 'data-provider-custom-json-rest',
                'auth-provider': 'none',
                'antd-example-pages': 'no',
                'mui-example-pages': 'no',
                'mantine-example-pages': 'no',
                'antd-custom-layout': 'no',
                'mui-custom-layout': 'no',
                'mantine-custom-layout': 'no',
                'command-palette': 'no',
                'i18n-no': 'no',
                'i18n-antd': 'no',
                'i18n-mui': 'no',
                'i18n-mantine': 'no',
                'partytown-builder': 'no',
                "inferencer": "no",
            }
        },
        {
            name: "refine-chakra-ui",
            type: "refine-react",
            answers: {
                'ui-framework': 'chakra',
                'mui-extend-theme': 'no',
                'mui-dark-mode': 'no',
                'mantine-dark-mode': 'no',
                'chakra-dark-mode': 'no',
                'router-provider': 'react-router-v6',
                'data-provider': 'data-provider-custom-json-rest',
                'auth-provider': 'none',
                'antd-example-pages': 'no',
                'mui-example-pages': 'no',
                'mantine-example-pages': 'no',
                'chakra-example-pages': 'no',
                'antd-custom-layout': 'no',
                'mui-custom-layout': 'no',
                'mantine-custom-layout': 'no',
                'chakra-custom-layout': 'no',
                'command-palette': 'no',
                'i18n-no': 'no',
                'i18n-antd': 'no',
                'i18n-mui': 'no',
                'i18n-mantine': 'no',
                'i18n-chakra': 'no',
                'partytown-builder': 'no',
                "inferencer": "no",
            }
        },
        {
            name: "refine-headless-remix",
            type: "refine-remix",
            answers: {
                "ui-framework": "no",
                "mui-extend-theme": "no",
                "mui-dark-mode": "no",
                "data-provider": "data-provider-custom-json-rest",
                "auth-provider": "none",
                "antd-example-pages": "no",
                "mui-example-pages": "no",
                "antd-custom-layout": "no",
                "mui-custom-layout": "no",
                "command-palette": "no",
                "inferencer": "no",
            },
        },
        {
            name: "refine-antd-nextjs",
            type: "refine-nextjs",
            answers: {
                "ui-framework": "antd",
                "mui-extend-theme": "no",
                "mui-dark-mode": "no",
                "data-provider": "data-provider-custom-json-rest",
                "auth-provider": "none",
                "antd-example-pages": "no",
                "mui-example-pages": "no",
                "antd-custom-layout": "no",
                "mui-custom-layout": "no",
                "command-palette": "no",
                "i18n-no": "no",
                "i18n-antd": "no",
                "i18n-mui": "no",
                "partytown-builder": "no",
                "inferencer": "no",
            },
        },
        {
            name: "refine-antd-supabase",
            type: "refine-react",
            answers: {
                "ui-framework": "antd",
                "mui-extend-theme": "no",
                "mui-dark-mode": "no",
                "router-provider": "react-router-v6",
                "data-provider": "data-provider-supabase",
                "auth-provider": "none",
                "antd-example-pages": "no",
                "mui-example-pages": "no",
                "antd-custom-layout": "no",
                "mui-custom-layout": "no",
                "command-palette": "no",
                "i18n-no": "no",
                "i18n-antd": "no",
                "i18n-mui": "no",
                "partytown-builder": "no",
            },
        },
    ],
};
