import { Metadata } from "next";
import React, { Suspense } from "react";
import { App } from "./_app";

export const metadata: Metadata = {
    title: "Refine",
    description: "Generated by create refine app",
    icons: {
        icon: "/favicon.ico",
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Suspense>
                    <App>{children}</App>
                </Suspense>
            </body>
        </html>
    );
}
